### ISSUE TITLE
Token is returned as URI fragment with a `#`, but is expected as query parameters

### ISSUE THREAD

**Issue by nstrelow** [supabase/gotrue-dart#12]
The login provider callback URL: `baseUrl/#accessToken=xyz`.

getSessionFromUrl expects the URL to use query params: `baseUrl/?accessToken=xyz`.

https://github.com/supabase/gotrue-dart/blob/main/lib/src/gotrue_client.dart#L109

@phamhieu Is this due to supabase incorrectly prepending `#` to the query params or should the dart-sdk be able to handle `baseUrl/#accessToken=xyz`, with a `#` ?

Original problem: baseUrl/#accessToken: Everything after # is stripped => This was due to using the url path strategy.

**Comment by phamhieu** [comment]
Hi @nstrelow, I will check with the backend team.

**Comment by awalias** [comment]
in this case `getSessionFromUrl` should be looking to parse the fragment instead of the query string, I believe the [backend](https://github.com/supabase/gotrue) was written this was so that a URI containing query string can still be used as a callback URL and the auth tokens can just be tagged on the end:

`my-callback-url.com?page=welcome&foo=bar#access_token=xyz`

**Comment by nstrelow** [comment]
This is now working as expected.

https://github.com/flutter/flutter/issues/80666 still remains.
It only concerns Flutter mobile (iOS, Android at least) and currently removes everything after `#` in a URL.
Until this is fixed, AFAIK it is not possible sign in with a provider (or use any callback URL with `#accessToken`) together with mobile deeplinks.

**Comment by phamhieu** [comment]
Fixed https://github.com/supabase/gotrue-dart/commit/95fb42f46a0a7ffaa35db651190ac5e3af8269ba

Thank you @nstrelow
